"""initial

Revision ID: 609304aa43d0
Revises: 
Create Date: 2026-02-12 14:27:42.333911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '609304aa43d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aio_data',
    sa.Column('taskId', sa.String(length=64), nullable=False, comment='任务ID'),
    sa.Column('RBData', mysql.LONGTEXT(), nullable=True),
    sa.Column('probCount', mysql.LONGTEXT(), nullable=True),
    sa.Column('totalTime', mysql.BIGINT(display_width=100), server_default=sa.text('0'), nullable=True),
    sa.Column('queueTime', mysql.BIGINT(display_width=100), server_default=sa.text('0'), nullable=True),
    sa.Column('compileTime', mysql.BIGINT(display_width=100), server_default=sa.text('0'), nullable=True),
    sa.Column('amendTime', mysql.BIGINT(display_width=100), server_default=sa.text('0'), nullable=True),
    sa.Column('aioExecuteTime', mysql.BIGINT(display_width=100), server_default=sa.text('0'), nullable=True),
    sa.Column('aioCompileTime', mysql.BIGINT(display_width=100), server_default=sa.text('0'), nullable=True),
    sa.Column('aioPendingTime', mysql.BIGINT(display_width=100), server_default=sa.text('0'), nullable=True),
    sa.Column('aioMeasureTime', mysql.BIGINT(display_width=100), server_default=sa.text('0'), nullable=True),
    sa.Column('aioPostProcessTime', mysql.BIGINT(display_width=100), server_default=sa.text('0'), nullable=True),
    sa.Column('aioTimeStamp', sa.String(length=256), server_default=sa.text('\'""\''), nullable=True),
    sa.Column('measureQubitSize', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('taskId'),
    sa.UniqueConstraint('taskId')
    )
    op.create_table('chip_data',
    sa.Column('chipId', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('qubitsUpdateTime', mysql.LONGTEXT(), nullable=False),
    sa.PrimaryKeyConstraint('chipId')
    )
    op.create_table('chip_exectime',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False, comment='id'),
    sa.Column('chip_id', mysql.BIGINT(display_width=20), nullable=False, comment='芯片ID'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='独占开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='独占结束时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='芯片独占时间表'
    )
    op.create_table('chip_fidelity_data',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('task_id', sa.String(length=256), nullable=True),
    sa.Column('state', mysql.INTEGER(display_width=11), server_default=sa.text('-1'), nullable=True),
    sa.Column('chip_id', sa.String(length=256), nullable=True),
    sa.Column('label', mysql.INTEGER(display_width=11), server_default=sa.text('1'), nullable=True),
    sa.Column('expand_task_num', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('update_time', mysql.BIGINT(display_width=100), nullable=True),
    sa.Column('ir_type', sa.String(length=256), nullable=True),
    sa.Column('fidelity_data', mysql.LONGTEXT(), nullable=True),
    sa.Column('schedule', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('start_time', mysql.BIGINT(display_width=100), nullable=True),
    sa.Column('end_time', mysql.BIGINT(display_width=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clops_test',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False, comment='主键ID'),
    sa.Column('max_batch_limits', mysql.BIGINT(display_width=20), nullable=True, comment='最大批次限制'),
    sa.Column('circuits_num', mysql.BIGINT(display_width=20), nullable=True, comment='线路数'),
    sa.Column('layers_num', mysql.BIGINT(display_width=20), nullable=True, comment='层数'),
    sa.Column('iterations', mysql.BIGINT(display_width=20), nullable=True, comment='迭代数'),
    sa.Column('chip_id', mysql.BIGINT(display_width=20), nullable=True, comment='芯片id'),
    sa.Column('is_amend', mysql.TINYINT(display_width=1), nullable=True, comment='是否修正'),
    sa.Column('is_mapping', mysql.TINYINT(display_width=1), nullable=True, comment='是否开启映射'),
    sa.Column('is_optimization', mysql.TINYINT(display_width=1), nullable=True, comment='是否开启线路优化'),
    sa.Column('clops', sa.Float(asdecimal=True), nullable=True, comment='clops结果'),
    sa.Column('status', mysql.BIGINT(display_width=4), nullable=True, comment='状态：1.已提交；2.异常；3.已完成'),
    sa.Column('error_info', sa.String(length=255), nullable=True, comment='异常信息'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='clops测试表'
    )
    op.create_table('cloud_user_SK',
    sa.Column('cloud_user_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('sk', mysql.LONGTEXT(), nullable=True),
    sa.Column('pk_id', sa.String(length=64), nullable=True),
    sa.Column('secret_key', mysql.LONGTEXT(), nullable=True),
    sa.Column('IV', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('cloud_user_id')
    )
    op.create_table('job_chip_mapping',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False, comment='主键ID'),
    sa.Column('job_id', sa.String(length=50), nullable=False, comment='定时任务ID'),
    sa.Column('chip_ids', sa.Text(), nullable=True, comment='芯片ID列表，以逗号分隔'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id'),
    comment='定时任务与芯片映射表'
    )
    op.create_table('m3_sample_info',
    sa.Column('info_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('chip_name', sa.String(length=45), nullable=True),
    sa.Column('label', mysql.TINYINT(display_width=4), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('start_time', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('end_time', mysql.BIGINT(display_width=20), nullable=True),
    sa.PrimaryKeyConstraint('info_id')
    )
    op.create_table('prof_compensate_angle',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('state', mysql.INTEGER(display_width=11), server_default=sa.text('1'), nullable=True),
    sa.Column('chip_id', sa.String(length=64), nullable=False),
    sa.Column('label', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('qubits', sa.String(length=64), nullable=True),
    sa.Column('depth', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('check_time', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('err_info', sa.String(length=64), nullable=True),
    sa.Column('compensate_angle', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiling_qprog',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('qprog', mysql.LONGTEXT(), nullable=False),
    sa.Column('qprog_qubit_num', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('qprog_depth', mysql.INTEGER(display_width=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiling_result',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('profiling_type', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('task_num', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('state', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('start_time', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('end_time', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('result', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiling_task',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('state', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('start_time', mysql.BIGINT(display_width=100), server_default=sa.text('0'), nullable=True),
    sa.Column('end_time', mysql.BIGINT(display_width=100), server_default=sa.text('0'), nullable=True),
    sa.Column('profiling_desc', sa.String(length=1024), server_default=sa.text("'0'"), nullable=True),
    sa.Column('is_develop', mysql.TINYINT(display_width=8), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiling_task_result',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('profiling_qprog_id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('profiling_task_id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('state', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('start_time', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('end_time', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('profiling_flag', sa.String(length=45), nullable=True),
    sa.Column('min_cpu_usage', sa.Float(asdecimal=True), nullable=True),
    sa.Column('max_cpu_usage', sa.Float(asdecimal=True), nullable=True),
    sa.Column('min_mem_usage', sa.Float(asdecimal=True), nullable=True),
    sa.Column('max_mem_usage', sa.Float(asdecimal=True), nullable=True),
    sa.Column('min_throughput', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('max_throughput', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('min_response_time', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('max_response_time', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('max_avg_compile_time', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('min_avg_compile_time', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('cur_quantum_utilization', sa.Float(asdecimal=True), nullable=True),
    sa.Column('max_quantum_utilization', sa.Float(asdecimal=True), nullable=True),
    sa.Column('cpu_kernel', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('memory', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('disk_type', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('flag', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiling_time_consume',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('profiling_task_result_id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('start_state', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('state_order', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('consume_time', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('is_pressure_test', mysql.TINYINT(display_width=4), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quartz_bean',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False, comment='任务id'),
    sa.Column('job_id', sa.String(length=50), nullable=True),
    sa.Column('job_Des', sa.String(length=50), nullable=True, comment=' 任务名称'),
    sa.Column('job_class', sa.String(length=50), nullable=True, comment='任务执行类'),
    sa.Column('status', mysql.INTEGER(display_width=11), nullable=True, comment='任务状态 测试环境全部改成0'),
    sa.Column('cron_expression', sa.String(length=50), nullable=True, comment='任务运行时间表达式'),
    sa.Column('server_ip', sa.String(length=20), nullable=True),
    sa.Column('receivers', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='定时任务'
    )
    op.create_table('sys_dict',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('type_code', sa.String(length=50), nullable=False, comment='字典类型编码（例如：gender, user_status）'),
    sa.Column('type_name', sa.String(length=100), nullable=False, comment='字典类型名称（例如：性别、用户状态）'),
    sa.Column('value', mysql.LONGTEXT(), nullable=False, comment='字典值（例如：男、女）'),
    sa.Column('label', sa.String(length=255), nullable=False, comment='显示标签'),
    sa.Column('sort', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True, comment='排序'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.Column('is_del', mysql.TINYINT(display_width=4), server_default=sa.text('0'), nullable=True, comment='是否删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='字典表'
    )
    op.create_table('sys_task_compile',
    sa.Column('task_id', sa.String(length=64), nullable=False, comment='任务ID'),
    sa.Column('task_compile_info', mysql.LONGTEXT(), nullable=True, comment='任务编译信息'),
    sa.Column('task_without_compensate_prog', mysql.LONGTEXT(), nullable=True, comment='串扰补偿前的量子程序'),
    sa.Column('convertQProg', mysql.LONGTEXT(), nullable=True),
    sa.Column('mappingQProg', mysql.LONGTEXT(), nullable=True),
    sa.Column('mappingQubit', sa.String(length=5000), server_default=sa.text('\'""\''), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('sys_user',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.CHAR(length=64), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=4), nullable=False),
    sa.Column('role_ids', mysql.TINYINT(display_width=4), nullable=False),
    sa.Column('vip', mysql.TINYINT(display_width=4), server_default=sa.text('1'), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.Column('realname', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('salt', sa.String(length=16), nullable=True),
    sa.Column('mark', mysql.TINYINT(display_width=4), server_default=sa.text('1'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='名'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='姓'),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=False, comment='手机号'),
    sa.Column('passport_number', sa.String(length=50), nullable=True, comment='护照号'),
    sa.Column('national_id', sa.String(length=50), nullable=True, comment='身份证号'),
    sa.Column('institution', sa.String(length=255), nullable=False, comment='所属机构'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_user_task',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False, comment='主键ID'),
    sa.Column('taskid', mysql.VARCHAR(length=64), nullable=False, comment='任务ID'),
    sa.Column('userid', mysql.BIGINT(display_width=20), nullable=False, comment='用户ID'),
    sa.Column('task_discribe', mysql.LONGTEXT(), nullable=True, comment='任务描述'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taskid')
    )
    op.create_table('task_info',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('cloud_user_for_pqc', mysql.INTEGER(display_width=11), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('task_status',
    sa.Column('taskId', sa.String(length=64), nullable=False, comment='taskId'),
    sa.Column('taskState', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=False, comment='taskState'),
    sa.Column('qProg', mysql.LONGTEXT(), nullable=False, comment='qProg'),
    sa.Column('qProgLength', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=False, comment='qProgLength'),
    sa.Column('qmType', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=False, comment='qmType'),
    sa.Column('backendType', sa.String(length=255), nullable=True, comment='backendType'),
    sa.Column('taskType', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=False, comment='taskType'),
    sa.Column('priority', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('configuration', mysql.LONGTEXT(), nullable=True),
    sa.Column('convertQProg', mysql.LONGTEXT(), nullable=True, comment='convertQProg'),
    sa.Column('mappingQProg', mysql.LONGTEXT(), nullable=True, comment='mappingQProg'),
    sa.Column('mappingQubit', sa.String(length=1024), server_default=sa.text("''"), nullable=False, comment='mappingQubit'),
    sa.Column('requiredCore', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=False, comment='requiredCore'),
    sa.Column('taskResult', mysql.LONGTEXT(), nullable=True, comment='taskResult'),
    sa.Column('probCount', mysql.LONGTEXT(), nullable=True, comment='probCount'),
    sa.Column('qSTResult', mysql.LONGTEXT(), nullable=True, comment='qSTResult'),
    sa.Column('qSTFidelity', mysql.LONGTEXT(), nullable=True, comment='qSTFidelity'),
    sa.Column('timeStr', mysql.LONGTEXT(), nullable=True, comment='timeStr'),
    sa.Column('startTime', mysql.BIGINT(display_width=20), nullable=True, comment='startTime'),
    sa.Column('endTime', mysql.BIGINT(display_width=20), nullable=True, comment='endTime'),
    sa.Column('timeStamp', sa.String(length=1024), server_default=sa.text("''"), nullable=True),
    sa.Column('errCode', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=False, comment='errCode'),
    sa.Column('errInfo', mysql.LONGTEXT(), nullable=True, comment='errInfo'),
    sa.Column('callbackAddr', sa.String(length=256), server_default=sa.text("''"), nullable=True, comment='callbackAddr'),
    sa.PrimaryKeyConstraint('taskId')
    )
    op.create_table('test_binary_data',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('binary_data', mysql.LONGBLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xeb_part_task',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False, comment='主键ID'),
    sa.Column('task_id', sa.String(length=64), nullable=False, comment='任务ID'),
    sa.Column('chip_id', sa.String(length=64), nullable=False, comment='芯片ID'),
    sa.Column('test_depth', sa.String(length=255), nullable=False, comment='测试深度'),
    sa.Column('test_bit', sa.String(length=255), nullable=False, comment='测试比特'),
    sa.Column('cron_expression', sa.String(length=255), nullable=False, comment='执行表达式'),
    sa.Column('enabled', mysql.TINYINT(display_width=4), server_default=sa.text('0'), nullable=True, comment='开启: 0-未开启, 1-已开启'),
    sa.Column('error_info', mysql.LONGTEXT(), nullable=True, comment='异常信息'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=4), server_default=sa.text('0'), nullable=True, comment='是否删除: 0-未删除, 1-已删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id'),
    comment='XEB局部任务'
    )
    op.create_table('xeb_part_task_detail',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False, comment='主键ID'),
    sa.Column('xeb_part_task_id', mysql.BIGINT(display_width=20), nullable=False, comment='XEB局部任务ID'),
    sa.Column('status', mysql.TINYINT(display_width=4), nullable=True, comment='状态：1.已提交；2.异常；3.已完成；4.已取消'),
    sa.Column('fidelity', sa.Float(asdecimal=True), nullable=True, comment='结果'),
    sa.Column('error_info', mysql.LONGTEXT(), nullable=True, comment='异常信息'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=4), server_default=sa.text('0'), nullable=True, comment='是否删除: 0-未删除, 1-已删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='XEB局部任务详情'
    )
    op.create_table('xeb_test',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False, comment='主键ID'),
    sa.Column('result', mysql.LONGTEXT(), nullable=True, comment='结果'),
    sa.Column('status', mysql.BIGINT(display_width=20), nullable=True, comment='状态：1.已提交；2.异常；3.已完成'),
    sa.Column('error_info', mysql.LONGTEXT(), nullable=True, comment='异常信息'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('pic_path', mysql.LONGTEXT(), nullable=True, comment='图片地址'),
    sa.Column('total_pic_path', sa.String(length=255), nullable=True, comment='总图地址'),
    sa.Column('task_id', sa.String(length=255), nullable=True, comment='算法推送的任务ID'),
    sa.Column('single_result', mysql.LONGTEXT(), nullable=True, comment='单门结果'),
    sa.Column('single_pic_path', mysql.LONGTEXT(), nullable=True, comment='单门图片地址'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=4), server_default=sa.text('0'), nullable=True, comment='是否删除: 0-未删除, 1-已删除'),
    sa.Column('progress', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True, comment='进度'),
    sa.Column('chip_id', sa.String(length=64), nullable=True, comment='芯片ID'),
    sa.Column('label', mysql.TINYINT(display_width=4), nullable=True, comment='工作标签'),
    sa.PrimaryKeyConstraint('id'),
    comment='XEBs测试表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xeb_test')
    op.drop_table('xeb_part_task_detail')
    op.drop_table('xeb_part_task')
    op.drop_table('test_binary_data')
    op.drop_table('task_status')
    op.drop_table('task_info')
    op.drop_table('sys_user_task')
    op.drop_table('sys_user')
    op.drop_table('sys_task_compile')
    op.drop_table('sys_dict')
    op.drop_table('quartz_bean')
    op.drop_table('profiling_time_consume')
    op.drop_table('profiling_task_result')
    op.drop_table('profiling_task')
    op.drop_table('profiling_result')
    op.drop_table('profiling_qprog')
    op.drop_table('prof_compensate_angle')
    op.drop_table('m3_sample_info')
    op.drop_table('job_chip_mapping')
    op.drop_table('cloud_user_SK')
    op.drop_table('clops_test')
    op.drop_table('chip_fidelity_data')
    op.drop_table('chip_exectime')
    op.drop_table('chip_data')
    op.drop_table('aio_data')
    # ### end Alembic commands ###
